#!/usr/bin/python

import imaplib
from accounts import accounts

try:
    obj = imaplib.IMAP4_SSL('imap.gmail.com', 993)
    obj.login(accounts.main_email, accounts.main_password)
    obj.select()
    print(len(obj.search(None, 'UnSeen')[1][0].split()))
except:
    print("N")
