#!/bin/python

import urllib.request, json

city = "Palma de Mallorca"
api_key = "3474b4c1c46d9fdfeee8070447166d8e"
units = "Metric"
unit_key = "C"

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}&units={}".format(city, api_key, units)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]))

print("%s %i °%s" % (info, temp, unit_key))
